--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DanteDEVS/EntityPM3
build-by-default: true
branches:
- main
projects:
  EntityPM3:
    path: ""
    model: virion
    type: library
...
